# This is a basic workflow that is manually triggered

name: Manual deploy to server

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Deploy to server
    
    steps:
    
    - name: git-checkout
      uses: actions/checkout@v2

    - name: Install all dependencies
      run: npm install

    - name: Build
      run: npm run build # The build command of your project
      
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }} 
        known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
        
    - name: Adding Known Hosts
      run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      
    - name: Deploy with rsync
      run: rsync -avz ./build ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/html/
